### ISSUE TITLE
Negative profit

### ISSUE THREAD

**Issue by Gudui** [llens/CryptoCurrencyTrader#23]
Just more curious to get a better insight of predicting the franctional profit as im recieving negative profit for ETH at the moment.

I've tried different combinations of steps, pages to craw, window size, and the two different types of preprocessing for the NLP aspekt. However, none of them seems to have an impact of the ngeative prediction profit.

Crawling USDT_ETH

Output:

Fitting time:  6.35607814789
Fractional profit compared to buy and hold:  -0.00282852266909
Mean squared error:  1.68302310242
Window:  150
Target step : 500
Fitting model:  tensorflow
Regression/classification:  regression
Number of trades:  1698
Offset:  100.0

**Comment by llens** [comment]
All profit is defined compared to buy and hold, as ethereum has been increasing pretty consistently, the algorithm probably can't beat buy and hold. (Or if trade fees and bid ask spread are enabled, it might be losing slighly more than it returns on the whole.)

For instance, if ETH goes up 10% and the algorithm only makes 8% I call that a 2% loss which a lot of the other projects don't. I need to start looking at sharpe ratio perhaps, because there is an advantage to the fact that the algortihm isn't in the market all the time.

**Comment by llens** [comment]
I have added a raw profit field to the output now to make it as clear as possible. (Raw profit, is now final portfolio value compared to initial portfolio value.)

**Comment by Gudui** [comment]
@llens 
What is the portfolio value defined as? It is not very clear for me, except it is defined from an buy_sell_lenth array. As I interpret portfolio value is the actual value that is my starting point for trading.
